"""
podcodex.core.correct — Transcript correction pipeline.

Corrects transcription errors in the source language without translating.

Modes:
    - manual  : user provides the corrected JSON directly (e.g. via a LLM UI)
    - ollama  : local LLM via Ollama
    - api     : external API (OpenAI, Anthropic, etc.)

Output:
    corrected/{id}.json  — versioned corrected segments (via version DB)
"""

from collections.abc import Callable
from pathlib import Path

from loguru import logger

from podcodex.core._utils import (
    DEFAULT_BATCH_MINUTES,
    AudioPaths,
    build_batched_manual_prompts,
    build_llm_prompt,
    format_segments,
    run_llm_pipeline,
)
from podcodex.core.pipeline_db import mark_step
from podcodex.core.versions import save_version


# ──────────────────────────────────────────────
# Prompt
# ──────────────────────────────────────────────


# Keyed by provenance source value → role template.
# {lang} and {model} are substituted at runtime.
_SOURCE_ROLES: dict[str, str] = {
    "whisper": "You are correcting a podcast transcript generated by Whisper {model} (automatic speech recognition) in {lang}.",
    "youtube-subtitles": "You are correcting a podcast transcript from YouTube auto-generated subtitles in {lang}.",
    "upload": "You are reviewing an uploaded podcast transcript in {lang}. It may contain minor errors.",
    "import": "You are reviewing an imported podcast transcript in {lang}. It may contain minor errors.",
}

_DEFAULT_ROLE = "You are correcting a podcast transcript in {lang}."


def transcript_provenance_info(provenance: dict | None) -> dict:
    """Extract source, model, and language from a transcript's provenance.

    Returns a dict with keys ``source``, ``model``, ``language`` (or None).
    Language is converted from ISO code to full name if needed.
    """
    from podcodex.core._utils import iso_to_language

    if not provenance:
        return {"source": "whisper", "model": None, "language": None}
    params = provenance.get("params", {})
    source = params.get("source", "whisper")
    model = provenance.get("model")
    # Normalize: both "language" and legacy "lang" keys
    lang_code = params.get("language") or params.get("lang")
    language = iso_to_language(lang_code) if lang_code else None
    return {"source": source, "model": model, "language": language}


def _build_prompt(
    context: str = "",
    source_lang: str = "French",
    engine: str = "whisper",
    engine_model: str | None = None,
) -> str:
    """Build the system prompt for transcript correcting."""
    role_template = _SOURCE_ROLES.get(engine, _DEFAULT_ROLE)
    model_str = f"({engine_model})" if engine_model else ""
    role = role_template.format(lang=source_lang, model=model_str).replace("  ", " ")
    return build_llm_prompt(
        role=role,
        task="""\
Your task: transcript correction only — do NOT translate.
- Fix automatic transcription errors (nonsensical words, phonetic mistakes)
- Keep the oral and conversational style — do not rephrase or restructure
- **Proper nouns:** names of people, brands, movies, and places are often misheard — correct their spelling. Use the context above as the authoritative source for any names or titles mentioned there.
- If a sentence is incomprehensible and unrecoverable, write [inaudible]
- Do NOT correct style, hesitations, or natural repetitions
- NEVER shorten, summarize or omit any part of the original text — every word matters""",
        output="""\
Output format — CRITICAL RULES:
1. Return a JSON array with EXACTLY the same number of elements as the input, in the SAME ORDER. Never merge, split, drop, add, or reorder segments.
2. Each element is a plain object with a single `text` field — no index, no other fields.
3. The Nth output element corresponds to the Nth input segment. Position is the only mapping.
4. If a segment is empty, trivial, or you cannot improve it, copy the original text verbatim — never omit the entry.
5. Reply ONLY with valid JSON. No surrounding text, no markdown fences, no commentary.
6. Format: `[{"text": "..."}, {"text": "..."}, ...]`

Example — input:
  [5] euh ouais c est ca
  [6] [music]
output:
  [{"text": "Euh, ouais, c'est ça."}, {"text": "[music]"}]""",
        context=context,
        context_extra=(
            "and must be used to fix phonetically similar but misspelled versions in the transcript "
            "(e.g. if the context says 'DeepMind', fix 'Deep Mind' → 'DeepMind')."
        ),
    )


# ──────────────────────────────────────────────
# Manual
# ──────────────────────────────────────────────


def build_manual_prompt(
    segments: list[dict],
    context: str = "",
    source_lang: str = "French",
    engine: str = "whisper",
    engine_model: str | None = None,
    start_index: int = 0,
) -> str:
    """Generate a prompt to paste into a LLM UI for manual correcting."""
    prompt = _build_prompt(
        context=context,
        source_lang=source_lang,
        engine=engine,
        engine_model=engine_model,
    )
    segments_text = format_segments(
        segments, instruction="Correct", start_index=start_index
    )
    return f"{prompt}\n\n{segments_text}"


def build_manual_prompts_batched(
    segments: list[dict],
    batch_minutes: float = DEFAULT_BATCH_MINUTES,
    context: str = "",
    source_lang: str = "French",
    engine: str = "whisper",
    engine_model: str | None = None,
) -> list[tuple[list[dict], str]]:
    """Split segments into time-based batches and return one prompt per batch."""
    return build_batched_manual_prompts(
        segments,
        lambda batch, start: build_manual_prompt(
            batch,
            context=context,
            source_lang=source_lang,
            engine=engine,
            engine_model=engine_model,
            start_index=start,
        ),
        batch_minutes,
    )


# ──────────────────────────────────────────────
# Public entry
# ──────────────────────────────────────────────


def correct_segments(
    segments: list[dict],
    mode: str = "ollama",
    context: str = "",
    source_lang: str = "French",
    model: str = "",
    api_base_url: str = "",
    api_key: str | None = None,
    batch_minutes: float = DEFAULT_BATCH_MINUTES,
    original_segments: list[dict] | None = None,
    merge: bool = True,
    max_gap: float = 10.0,
    provider: str | None = None,
    engine: str = "whisper",
    engine_model: str | None = None,
    on_batch: Callable[[int, int], None] | None = None,
) -> list[dict]:
    """Correct transcription errors in segments."""
    logger.info(f"Correcting {len(segments)} segments — mode={mode}")
    system_prompt = _build_prompt(
        context, source_lang=source_lang, engine=engine, engine_model=engine_model
    )
    result = run_llm_pipeline(
        segments,
        system_prompt,
        mode=mode,
        model=model,
        api_base_url=api_base_url,
        api_key=api_key,
        batch_minutes=batch_minutes,
        provider=provider,
        instruction="Correct",
        label="Correct",
        original_segments=original_segments,
        merge=merge,
        max_gap=max_gap,
        on_batch=on_batch,
    )
    logger.success(f"Correct done — {len(result)} segments")
    return result


# ──────────────────────────────────────────────
# Persistence
# ──────────────────────────────────────────────


def save_corrected(
    audio_path: Path | str,
    segments: list[dict],
    output_dir: str | Path | None = None,
    provenance: dict | None = None,
) -> str:
    """Save corrected segments (version DB + pipeline DB). Returns the version id."""
    p = AudioPaths.from_audio(audio_path, output_dir=output_dir)
    version_id = save_version(p.base, "corrected", segments, provenance)
    logger.info(f"Corrected saved → {p.base.name} ({len(segments)} segments)")
    prov_update = {"corrected": provenance} if provenance else {}
    mark_step(p.show_dir, p.base.name, corrected=True, provenance=prov_update)
    return version_id
