"""
podcodex.core.polish — Transcript correction pipeline.

Corrects transcription errors in the source language without translating.

Modes:
    - manual  : user provides the corrected JSON directly (e.g. via a LLM UI)
    - ollama  : local LLM via Ollama
    - api     : external API (OpenAI, Anthropic, etc.)

Output files:
    {stem}.polished.raw.json  — pipeline output (unvalidated)
    {stem}.polished.json      — validated/edited polished transcript
"""

import json

from pathlib import Path

from loguru import logger

from podcodex.core._utils import (
    AudioPaths,
    batch_segments_by_duration,
    merge_consecutive_segments,
    read_json,
    run_api,
    run_ollama,
    save_segments_json,
    validate_manual,
)


# ──────────────────────────────────────────────
# Prompt
# ──────────────────────────────────────────────


def _build_prompt(
    context: str = "", source_lang: str = "French", engine: str = "Whisper"
) -> str:
    """Build the system prompt for transcript polishing.

    Args:
        context     : podcast context (names, topics) to guide spelling corrections
        source_lang : source language (e.g. "French")
        engine      : transcription engine name (e.g. "Whisper", "Voxtral")
    """
    role = f"You are correcting a transcript from a podcast generated by {engine} in {source_lang}."

    context_section = (
        f"Context about this podcast: {context}\n"
        "Any names, titles, brands, or terms mentioned in the context above are the CORRECT spellings "
        "and must be used to fix phonetically similar but misspelled versions in the transcript "
        "(e.g. if the context says 'DeepMind', fix 'Deep Mind' → 'DeepMind')."
        if context
        else ""
    )

    task = """\
Your task: transcript correction only — do NOT translate.
- Fix automatic transcription errors (nonsensical words, phonetic mistakes)
- Keep the oral and conversational style — do not rephrase or restructure
- **Proper nouns:** names of people, brands, movies, and places are often misheard by Whisper — correct their spelling. Use the context above as the authoritative source for any names or titles mentioned there.
- If a sentence is incomprehensible and unrecoverable, write [inaudible]
- Do NOT correct style, hesitations, or natural repetitions
- NEVER shorten, summarize or omit any part of the original text — every word matters
- Segments with speaker "[BREAK]" are music or jingle breaks — copy them to the output exactly as-is, do not modify their text"""

    output = """\
Output format:
Return a JSON array with EXACTLY the same number of elements as the input — never merge, split, or drop segments.
Each output element must have the corrected text field for the corresponding input element.
Reply ONLY with valid JSON, no surrounding text, no markdown.
Format: [{"index": 0, "text": "..."}]  — include only index and text fields."""

    sections = [role, context_section, task, output]
    return "\n\n".join(s for s in sections if s)


# ──────────────────────────────────────────────
# Manual
# ──────────────────────────────────────────────


def build_manual_prompt(
    segments: list[dict],
    context: str = "",
    source_lang: str = "French",
) -> str:
    """Generate a prompt to paste into a LLM UI for manual polishing.

    Combines the system prompt from ``_build_prompt`` with the
    segments JSON so the user can paste a single block into any LLM UI.
    """
    prompt = _build_prompt(context=context, source_lang=source_lang)
    segments_json = json.dumps(segments, ensure_ascii=False, indent=2)
    return f"{prompt}\n\n{segments_json}"


def build_manual_prompts_batched(
    segments: list[dict],
    batch_minutes: float = 15.0,
    context: str = "",
    source_lang: str = "French",
) -> list[tuple[list[dict], str]]:
    """Split segments into time-based batches and return one prompt per batch.

    Args:
        segments      : transcript segments to batch
        batch_minutes : maximum duration per batch in minutes (default 15)
        context       : podcast context to include in each prompt
        source_lang   : source language (e.g. "French")

    Returns:
        List of (batch_segments, prompt_string) tuples.
    """
    return [
        (batch, build_manual_prompt(batch, context=context, source_lang=source_lang))
        for batch in batch_segments_by_duration(segments, batch_minutes)
    ]


# ──────────────────────────────────────────────
# Public entry
# ──────────────────────────────────────────────


def polish_segments(
    segments: list[dict],
    mode: str = "ollama",
    context: str = "",
    source_lang: str = "French",
    model: str = "",
    api_base_url: str = "",
    api_key: str | None = None,
    batch_size: int = 10,
    merge: bool = True,
    max_gap: float = 10.0,
    engine: str = "Whisper",
    provider: str | None = None,
    original_segments: list[dict] | None = None,
) -> list[dict]:
    """
    Correct transcription errors in segments.

    Args:
        segments          : transcript segments (for ollama/api mode),
                            or LLM output with corrections (for manual mode)
        mode              : "manual", "ollama", or "api"
        context           : podcast context to guide the LLM
        source_lang       : source language (e.g. "French")
        model             : LLM model name (auto-detected from provider if empty)
        api_base_url      : base URL for OpenAI-compatible API (auto-detected from provider if empty)
        api_key           : API key (None reads from provider's env variable)
        batch_size        : number of segments per LLM call
        merge             : merge consecutive same-speaker segments before processing (default True)
        max_gap           : maximum silence gap in seconds for merging (default 10.0)
        engine            : transcription engine name for the prompt (default "Whisper")
        provider          : provider shorthand ("openai", "anthropic", "mistral", "groq")
                            — sets api_base_url, model, and api_key env var automatically
        original_segments : only for manual mode — the original source segments
                            (used to merge metadata with the LLM-provided corrections)

    Returns:
        List of segments with corrected text field.
    """
    logger.info(f"Polishing {len(segments)} segments — mode={mode}")
    logger.debug(
        f"Polish params: lang={source_lang}, engine={engine}, batch_size={batch_size}, merge={merge}"
    )
    if context:
        logger.debug(f"Context: {context[:100]}{'…' if len(context) > 100 else ''}")

    if mode == "manual":
        orig = original_segments if original_segments is not None else segments
        return validate_manual(segments, orig)

    if merge:
        segments = merge_consecutive_segments(segments, max_gap=max_gap)
        logger.info(f"After merge: {len(segments)} segments")

    system_prompt = _build_prompt(context, source_lang=source_lang, engine=engine)

    if mode == "ollama":
        result = run_ollama(
            segments,
            system_prompt,
            model=model or "qwen3:4b",
            batch_size=batch_size,
            instruction="Correct",
            label="Polish",
        )
    elif mode == "api":
        result = run_api(
            segments,
            system_prompt,
            model=model,
            api_base_url=api_base_url,
            api_key=api_key,
            batch_size=batch_size,
            provider=provider,
            instruction="Correct",
            label="Polish",
        )
    else:
        raise ValueError(
            f"Unknown mode: {mode!r}. Choose from 'manual', 'ollama', 'api'."
        )

    logger.success(f"Polish done — {len(result)} segments")
    return result


# ──────────────────────────────────────────────
# Persistence
# ──────────────────────────────────────────────


def save_polished_raw(
    audio_path: Path | str,
    segments: list[dict],
    output_dir: str | Path | None = None,
    nodiar: bool = False,
) -> Path:
    """Save pipeline-generated polished segments to {stem}.polished.raw.json.

    Use this for LLM/pipeline output. The user can then review and promote
    to the validated {stem}.polished.json.
    """
    p = AudioPaths.from_audio(audio_path, output_dir=output_dir, nodiar=nodiar)
    return save_segments_json(p.polished_raw, segments, "Polished transcript")


def save_polished(
    audio_path: Path | str,
    segments: list[dict],
    output_dir: str | Path | None = None,
    nodiar: bool = False,
) -> Path:
    """Save validated/edited polished segments to {stem}.polished.json."""
    p = AudioPaths.from_audio(audio_path, output_dir=output_dir, nodiar=nodiar)
    return save_segments_json(p.polished, segments, "Polished transcript")


def load_polished(
    audio_path: Path | str,
    output_dir: str | Path | None = None,
    nodiar: bool = False,
) -> list[dict]:
    """Load polished segments. Prefers validated .polished.json, falls back to .polished.raw.json."""
    p = AudioPaths.from_audio(audio_path, output_dir=output_dir, nodiar=nodiar)
    return read_json(p.polished_best)


def load_polished_raw(
    audio_path: Path | str,
    output_dir: str | Path | None = None,
    nodiar: bool = False,
) -> list[dict]:
    """Load specifically from .polished.raw.json (pipeline output)."""
    p = AudioPaths.from_audio(audio_path, output_dir=output_dir, nodiar=nodiar)
    return read_json(p.polished_raw)


def load_polished_validated(
    audio_path: Path | str,
    output_dir: str | Path | None = None,
    nodiar: bool = False,
) -> list[dict]:
    """Load specifically from .polished.json (user-validated)."""
    p = AudioPaths.from_audio(audio_path, output_dir=output_dir, nodiar=nodiar)
    return read_json(p.polished)
