"""
podcodex.core.polish — Transcript correction pipeline.

Corrects transcription errors in the source language without translating.

Modes:
    - manual  : user provides the corrected JSON directly (e.g. via a LLM UI)
    - ollama  : local LLM via Ollama
    - api     : external API (OpenAI, Anthropic, etc.)

Output:
    .versions/polished/{id}.json  — versioned polished segments (via version DB)
"""

from collections.abc import Callable
from pathlib import Path

from loguru import logger

from podcodex.core._utils import (
    DEFAULT_BATCH_MINUTES,
    AudioPaths,
    batch_segments_by_duration,
    build_llm_prompt,
    format_segments,
    run_llm_pipeline,
)
from podcodex.core.pipeline_db import mark_step
from podcodex.core.versions import save_version


# ──────────────────────────────────────────────
# Prompt
# ──────────────────────────────────────────────


def _build_prompt(
    context: str = "", source_lang: str = "French", engine: str = "Whisper"
) -> str:
    """Build the system prompt for transcript polishing."""
    return build_llm_prompt(
        role=f"You are correcting a transcript from a podcast generated by {engine} in {source_lang}.",
        task="""\
Your task: transcript correction only — do NOT translate.
- Fix automatic transcription errors (nonsensical words, phonetic mistakes)
- Keep the oral and conversational style — do not rephrase or restructure
- **Proper nouns:** names of people, brands, movies, and places are often misheard by Whisper — correct their spelling. Use the context above as the authoritative source for any names or titles mentioned there.
- If a sentence is incomprehensible and unrecoverable, write [inaudible]
- Do NOT correct style, hesitations, or natural repetitions
- NEVER shorten, summarize or omit any part of the original text — every word matters""",
        output="""\
Output format:
Return a JSON array with EXACTLY the same number of elements as the input — never merge, split, or drop segments.
Each output element must have the corrected text field for the corresponding input element.
Reply ONLY with valid JSON, no surrounding text, no markdown.
Format: [{"index": 0, "text": "..."}]  — include only index and text fields.""",
        context=context,
        context_extra=(
            "and must be used to fix phonetically similar but misspelled versions in the transcript "
            "(e.g. if the context says 'DeepMind', fix 'Deep Mind' → 'DeepMind')."
        ),
    )


# ──────────────────────────────────────────────
# Manual
# ──────────────────────────────────────────────


def build_manual_prompt(
    segments: list[dict],
    context: str = "",
    source_lang: str = "French",
    engine: str = "Whisper",
) -> str:
    """Generate a prompt to paste into a LLM UI for manual polishing."""
    prompt = _build_prompt(context=context, source_lang=source_lang, engine=engine)
    segments_text = format_segments(segments, instruction="Correct")
    return f"{prompt}\n\n{segments_text}"


def build_manual_prompts_batched(
    segments: list[dict],
    batch_minutes: float = DEFAULT_BATCH_MINUTES,
    context: str = "",
    source_lang: str = "French",
    engine: str = "Whisper",
) -> list[tuple[list[dict], str]]:
    """Split segments into time-based batches and return one prompt per batch."""
    return [
        (
            batch,
            build_manual_prompt(
                batch, context=context, source_lang=source_lang, engine=engine
            ),
        )
        for batch in batch_segments_by_duration(segments, batch_minutes)
    ]


# ──────────────────────────────────────────────
# Public entry
# ──────────────────────────────────────────────


def polish_segments(
    segments: list[dict],
    mode: str = "ollama",
    context: str = "",
    source_lang: str = "French",
    model: str = "",
    api_base_url: str = "",
    api_key: str | None = None,
    batch_minutes: float = DEFAULT_BATCH_MINUTES,
    original_segments: list[dict] | None = None,
    merge: bool = True,
    max_gap: float = 10.0,
    provider: str | None = None,
    engine: str = "Whisper",
    on_batch: Callable[[int, int], None] | None = None,
) -> list[dict]:
    """Correct transcription errors in segments."""
    logger.info(f"Polishing {len(segments)} segments — mode={mode}")
    system_prompt = _build_prompt(context, source_lang=source_lang, engine=engine)
    result = run_llm_pipeline(
        segments,
        system_prompt,
        mode=mode,
        model=model,
        api_base_url=api_base_url,
        api_key=api_key,
        batch_minutes=batch_minutes,
        provider=provider,
        instruction="Correct",
        label="Polish",
        original_segments=original_segments,
        merge=merge,
        max_gap=max_gap,
        on_batch=on_batch,
    )
    logger.success(f"Polish done — {len(result)} segments")
    return result


# ──────────────────────────────────────────────
# Persistence
# ──────────────────────────────────────────────


def save_polished(
    audio_path: Path | str,
    segments: list[dict],
    output_dir: str | Path | None = None,
    provenance: dict | None = None,
) -> str:
    """Save polished segments (version DB + pipeline DB). Returns the version id."""
    p = AudioPaths.from_audio(audio_path, output_dir=output_dir)
    version_id = save_version(p.base, "polished", segments, provenance)
    prov_update = {"polished": provenance} if provenance else {}
    mark_step(p.show_dir, p.base.name, polished=True, provenance=prov_update)
    return version_id


save_polished_raw = save_polished
