"""
podcodex.core.polish — Transcript correction pipeline.

Corrects transcription errors in the source language without translating.

Modes:
    - manual  : user provides the corrected JSON directly (e.g. via a LLM UI)
    - ollama  : local LLM via Ollama
    - api     : external API (OpenAI, Anthropic, etc.)

Output file:
    {stem}.polished.json  — corrected source-language segments (merged, text field only)
"""

import json
import os
from pathlib import Path

from loguru import logger

from podcodex.core._paths import episode_output_dir


# ──────────────────────────────────────────────
# Paths
# ──────────────────────────────────────────────


def _polished_json(audio_path: Path, output_dir: str | Path | None = None) -> Path:
    return (
        episode_output_dir(audio_path, output_dir) / f"{audio_path.stem}.polished.json"
    )


# ──────────────────────────────────────────────
# Prompt
# ──────────────────────────────────────────────


def _build_polish_prompt(context: str = "", source_lang: str = "French") -> str:
    context_block = (
        f"Context about this podcast: {context}\n"
        f"Any names, titles, brands, or terms mentioned in the context above are the CORRECT spellings "
        f"and must be used to fix phonetically similar but misspelled versions in the transcript "
        f"(e.g. if the context says 'DeepMind', fix 'Deep Mind' → 'DeepMind')."
        if context
        else ""
    )
    return f"""You are correcting a transcript from a podcast generated by Whisper in {source_lang}.
{context_block}

Your task: transcript correction only — do NOT translate.
- Fix automatic transcription errors (nonsensical words, phonetic mistakes)
- Keep the oral and conversational style — do not rephrase or restructure
- **Proper nouns:** names of people, brands, movies, and places are often misheard by Whisper — correct their spelling. Use the context above as the authoritative source for any names or titles mentioned there.
- If a sentence is incomprehensible and unrecoverable, write [inaudible]
- Do NOT correct style, hesitations, or natural repetitions
- NEVER shorten, summarize or omit any part of the original text — every word matters

Output format:
Return a JSON array with exactly the same elements, with the corrected text field.
Reply ONLY with valid JSON, no surrounding text, no markdown.
Format: [{{"index": 0, "text": "..."}}]  — include only index and text fields."""


# ──────────────────────────────────────────────
# Core processing
# ──────────────────────────────────────────────


def _polish_batch(
    batch: list[dict],
    system_prompt: str,
    call_fn,
    min_length_ratio: float = 0.7,
) -> list[dict]:
    """
    Polish a single batch of segments using the provided call function.
    call_fn(messages) -> raw response string
    """
    import re

    user_content = "\n\n".join(f"[{i}] {seg['text']}" for i, seg in enumerate(batch))
    user_content += f"\n\nCorrect all {len(batch)} numbered segments above."

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_content},
    ]

    raw = call_fn(messages)
    raw = re.sub(r"<think>.*?</think>", "", raw, flags=re.DOTALL).strip()
    raw = re.sub(r"^```(?:json)?|```$", "", raw, flags=re.MULTILINE).strip()

    try:
        parsed = json.loads(raw)
        by_index = {item.get("index", i): item for i, item in enumerate(parsed)}
    except Exception as e:
        logger.warning(f"Parse error: {e} — batch will keep original text only")
        by_index = {}

    results = []
    for i, seg in enumerate(batch):
        item = by_index.get(i, {})
        original_text = seg["text"]
        corrected_text = item.get("text", original_text)

        if len(corrected_text) < len(original_text) * min_length_ratio:
            logger.warning(
                f"Segment [{i}] truncated by LLM "
                f"({len(corrected_text)} vs {len(original_text)} chars) — keeping original"
            )
            corrected_text = original_text

        entry = {**seg, "text": corrected_text}
        entry.pop("index", None)
        results.append(entry)

    return results


def _polish_ollama(
    segments: list[dict],
    context: str,
    source_lang: str,
    model: str,
    batch_size: int,
) -> list[dict]:
    from ollama import Client

    client = Client()
    system_prompt = _build_polish_prompt(context, source_lang=source_lang)
    results = []

    for i in range(0, len(segments), batch_size):
        batch = segments[i : i + batch_size]
        logger.info(
            f"Polish batch {i // batch_size + 1}/{-(-len(segments) // batch_size)} via Ollama ({model})"
        )

        def call_fn(messages):
            response = client.chat(
                model=model,
                messages=messages,
                options={"temperature": 0},
                format="json",
            )
            return response.message.content.strip()

        results.extend(_polish_batch(batch, system_prompt, call_fn))

    return results


def _polish_api(
    segments: list[dict],
    context: str,
    source_lang: str,
    model: str,
    api_base_url: str,
    api_key: str | None,
    batch_size: int,
) -> list[dict]:
    from openai import OpenAI

    key = api_key or os.environ.get("API_KEY")
    if not key:
        raise ValueError(
            "No API key found. Set API_KEY in your .env file, or pass api_key=."
        )

    client = OpenAI(api_key=key, base_url=api_base_url)
    system_prompt = _build_polish_prompt(context, source_lang=source_lang)
    results = []

    for i in range(0, len(segments), batch_size):
        batch = segments[i : i + batch_size]
        logger.info(
            f"Polish batch {i // batch_size + 1}/{-(-len(segments) // batch_size)} via API ({model})"
        )

        def call_fn(messages):
            response = client.chat.completions.create(
                model=model, messages=messages, temperature=0
            )
            return response.choices[0].message.content.strip()

        results.extend(_polish_batch(batch, system_prompt, call_fn))

    return results


def _validate_manual_polish(segments: list[dict]) -> list[dict]:
    """Validate that all segments have the text field."""
    required = {"speaker", "start", "end", "text"}
    for i, seg in enumerate(segments):
        missing = required - seg.keys()
        if missing:
            raise ValueError(
                f"Manual mode: segment [{i}] is missing fields {sorted(missing)}."
            )
    for seg in segments:
        seg.pop("index", None)
    logger.info(f"Manual polish validated — {len(segments)} segments")
    return segments


def polish_segments(
    segments: list[dict],
    mode: str = "ollama",
    context: str = "",
    source_lang: str = "French",
    model: str = "",
    api_base_url: str = "https://api.openai.com/v1",
    api_key: str | None = None,
    batch_size: int = 10,
) -> list[dict]:
    """
    Correct transcription errors in segments without translating.

    Args:
        segments    : output of simplify_transcript()
        mode        : "manual", "ollama", or "api"
        context     : podcast context to guide the LLM
        source_lang : source language (e.g. "French")
        model       : LLM model name
        api_base_url: base URL for OpenAI-compatible API
        api_key     : API key (None reads from API_KEY env variable)
        batch_size  : number of segments per LLM call

    Returns:
        List of segments with corrected text field.
    """
    if mode == "manual":
        return _validate_manual_polish(segments)
    elif mode == "ollama":
        return _polish_ollama(
            segments,
            context=context,
            source_lang=source_lang,
            model=model or "qwen3:4b",
            batch_size=batch_size,
        )
    elif mode == "api":
        return _polish_api(
            segments,
            context=context,
            source_lang=source_lang,
            model=model or "gpt-4o",
            api_base_url=api_base_url,
            api_key=api_key,
            batch_size=batch_size,
        )
    else:
        raise ValueError(
            f"Unknown mode: {mode!r}. Choose from 'manual', 'ollama', 'api'."
        )


# ──────────────────────────────────────────────
# Persistence
# ──────────────────────────────────────────────


def save_polished(
    audio_path: Path | str,
    segments: list[dict],
    output_dir: str | Path | None = None,
) -> Path:
    """Save polished segments to {stem}.polished.json (strips text_trad if present)."""
    audio_path = Path(audio_path)
    clean = [{k: v for k, v in s.items() if k != "text_trad"} for s in segments]
    out = _polished_json(audio_path, output_dir=output_dir)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(clean, indent=2, ensure_ascii=False), encoding="utf-8")
    logger.success(f"Polished transcript saved — {len(clean)} segments → {out.name}")
    return out


def load_polished(
    audio_path: Path | str, output_dir: str | Path | None = None
) -> list[dict]:
    """Load polished segments from {stem}.polished.json."""
    return json.loads(
        _polished_json(Path(audio_path), output_dir=output_dir).read_text(
            encoding="utf-8"
        )
    )


def polished_exists(
    audio_path: Path | str, output_dir: str | Path | None = None
) -> bool:
    return _polished_json(Path(audio_path), output_dir=output_dir).exists()


# ──────────────────────────────────────────────
# Export
# ──────────────────────────────────────────────


def polished_to_text(segments: list[dict]) -> str:
    """Format polished segments as plain readable text."""
    lines = [
        f"[{s['start']:.3f}s - {s['end']:.3f}s] {s['speaker']}\n{s['text']}"
        for s in segments
    ]
    return "\n\n".join(lines)


# ──────────────────────────────────────────────
# Manual translation helper
# ──────────────────────────────────────────────


def build_manual_polish_prompt(
    segments: list[dict],
    context: str = "",
    source_lang: str = "French",
) -> str:
    """Generate a prompt to paste into a LLM UI for manual polishing."""
    segments_json = json.dumps(segments, ensure_ascii=False, indent=2)
    instruction = (
        f"Correct the transcription errors in the {len(segments)} segments below.\n"
        "Return the SAME JSON array with only the 'text' field corrected. "
        "Keep all other fields (speaker, start, end, etc.) exactly as-is. "
        "Do not add, remove, or rename any fields. "
        "Reply ONLY with valid JSON, no surrounding text, no markdown."
    )
    if context:
        context_block = (
            f"Context about this podcast: {context}\n"
            f"Any names, titles, brands, or terms mentioned in the context above are the CORRECT spellings "
            f"and must be used to fix phonetically similar but misspelled versions in the transcript "
            f"(e.g. if the context says 'DeepMind', fix 'Deep Mind' → 'DeepMind').\n\n"
        )
    else:
        context_block = ""
    return f"{context_block}{instruction}\n\n{segments_json}"


def build_manual_polish_prompts_batched(
    segments: list[dict],
    batch_minutes: float = 15.0,
    context: str = "",
    source_lang: str = "French",
) -> list[tuple[list[dict], str]]:
    """Split segments into batches and return one prompt per batch."""
    max_seconds = batch_minutes * 60
    batches: list[list[dict]] = []
    current: list[dict] = []
    current_duration = 0.0

    for seg in segments:
        seg_duration = seg.get("end", 0) - seg.get("start", 0)
        if current and current_duration + seg_duration > max_seconds:
            batches.append(current)
            current = []
            current_duration = 0.0
        current.append(seg)
        current_duration += seg_duration

    if current:
        batches.append(current)

    return [
        (
            batch,
            build_manual_polish_prompt(batch, context=context, source_lang=source_lang),
        )
        for batch in batches
    ]
